name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: elementary/docker:unstable
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libgranite-dev libpolkit-gobject-1-dev libswitchboard-2.0-dev libzeitgeist-2.0-dev meson policykit-1 valac
    - name: Build
      run: |
        meson build
        ninja -C build
